### ISSUE TITLE
运行环境

### ISSUE THREAD

**Issue by yangxulin** [whisperLiang/Efficientnet_pytorch_cbam_gui#1]
大佬，可以发一下完整的requirements.txt吗？

**Comment by yangxulin** [comment]
奥，是因为train.py多了一行 import tensorflow as tf，注释掉就没问题了

**Comment by whisperLiang** [comment]
我在google colab是运行就是这些环境，可能主要就是安装torch那些，你那边提示还差什么环境吗？------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月2日(星期天) 晚上9:02
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[whisperLiang/Efficientnet_pytorch_cbam_gui] 运行环境 (#1)
